name: hvai
channels:
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - deprecated=1.2.13
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.7.1
  - filelock=3.17.0
  - fsspec=2025.7.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - libabseil=20250127.0
  - libcxx=19.1.7
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libtorch=2.6.0
  - libuv=1.48.0
  - llvm-openmp=19.1.7
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=3.0
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openpyxl=3.1.5
  - openssl=3.0.17
  - opentelemetry-api=1.30.0
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pip=25.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytorch=2.6.0
  - pytz=2025.2
  - pyzmq=26.2.0
  - readline=8.3
  - setuptools=72.1.0
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.50.2
  - stack_data=0.2.0
  - sympy=1.13.3
  - tk=8.6.15
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025b
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
